export const SOLICITUD_ESTADO = {
  BORRADOR: 'BORRADOR',
  ENVIADA: 'ENVIADA',
  EN_REVISION: 'EN_REVISION',
  CORRECCION: 'CORRECCION',
  EVALUADA: 'EVALUADA',
  APROBADA: 'APROBADA',
  RECHAZADA: 'RECHAZADA',
} as const;

export const CONVOCATORIA_ESTADO = {
  BORRADOR: 'BORRADOR',
  ABIERTA: 'ABIERTA',
  CERRADA: 'CERRADA',
  EN_EVALUACION: 'EN_EVALUACION',
  RESUELTA: 'RESUELTA',
  ARCHIVADA: 'ARCHIVADA',
} as const;

export const SESION_ESTADO = {
  FINALIZADA: 'FINALIZADA',
} as const;

export const DECISION_RESULTADO = {
  APROBADA: 'APROBADA',
  RECHAZADA: 'RECHAZADA',
} as const;

export const DOCUMENTO_ESTADO = {
  PENDIENTE: 'PENDIENTE',
  CARGADO: 'CARGADO',
  RECHAZADO: 'RECHAZADO',
} as const;
